In [119]:
#Q1
import numpy as np

def have_zeros(n):
      if np.all(n):
            print("None of the elements in the array is zero")
      else :
        print('The array have Zeros')
        
a=[1,1,3,4,5,5]
have_zeros(a)

b=[1,0,3,4,5,5]
have_zeros(b)

None of the elements in the array is zero
The array have Zeros


In [122]:
#Q2
 
def have_zeros(n):
    count=0
    for i in n:
        if i!=0:
             count+=1
    res=len(n)-(len(n)-count)
    print (res, 'elements are non-zero')
    
a=[1,1,3,4,5,5]
have_zeros(a)

b=[1,0,3,4,5,5]
have_zeros(b)

6 elements are non-zero
5 elements are non-zero


In [125]:
#Q3
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,3,3,5,4])
equal=np.equal(arr1,arr2)
print(equal)
equal_tol=np.allclose(arr1,arr2)
print(equal_tol)


[ True False  True False False]
False


In [25]:
#Q4
zeros=np.zeros(10)
print(zeros)

ones=np.ones(10)
print(ones)

fives=np.ones(10)*5
print(fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [27]:
#Q5
a=np.arange(30,71)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [34]:
#Q6
from numpy import matlib 

m=matlib.eye((3))
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [117]:
#Q7
from numpy import random

r=random.rand(1)
print(r)



[0.45439845]


In [116]:
#Q8
arr=random.rand(15)
print(arr)

[0.85193806 0.53096955 0.72297852 0.01025028 0.92341128 0.28881778
 0.7314702  0.35822321 0.83899233 0.73700617 0.30252699 0.47555585
 0.34673122 0.27352574 0.4241831 ]


In [44]:
#Q9
import numpy as np
v=np.arange(15,56)
for i in range(1,len(v)-1):
    print(v[i])


16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [126]:
#Q10
import numpy as np
from numpy import random
v=np.empty(5)
for i in range(len(v)):
    v[i]=random.randint(0,11)
print(v)
    


[ 2.  2.  0.  4. 10.]


In [83]:
#Q11       borders 1, inside 0
from numpy import matlib
m=matlib.ones((10,10))
m[1:-1,1:-1]=0
print(m)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [92]:
#Q12        5x5 zero, main diagonal 1 2 3 4 5
m=matlib.zeros((5,5))
for i in range(len(m)):
    for j in range(i,i+1):
        m[i,j]=i+1
print(m)        

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [103]:
#Q13
import numpy as np
from numpy import random

m=matlib.ones((4,4))
for i in range(len(m)):
    for j in range(i,i+1):
        m[i,j]=0
m

matrix([[0., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 1., 0., 1.],
        [1., 1., 1., 0.]])

In [153]:
#Q14
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,0])
arr2=np.array([0,9,8,7,6,5,4,3,2,1])
np.savez('file.npz',x=arr1,y=arr2)
f=np.load('file.npz')
print(f['x'])

[1 2 3 4 5 6 7 8 9 0]


In [74]:
#Q15
from numpy import random
arr=random.rand(40)
print(arr)

[0.02037116 0.25994773 0.90058639 0.51506238 0.16011278 0.02747912
 0.17799453 0.88365664 0.21889761 0.09491407 0.33130107 0.69460201
 0.07485065 0.19033556 0.14763676 0.6956249  0.35537882 0.93285398
 0.56038335 0.39942299 0.13279203 0.57189023 0.47748561 0.192469
 0.46031957 0.7757261  0.42428029 0.79786088 0.5261501  0.69634031
 0.28819038 0.40710958 0.38341043 0.84852603 0.11160854 0.43371547
 0.55425572 0.77909757 0.52248641 0.26761034]


In [63]:
#Q16
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,0])
x=5
List=[]
for i in arr:
    if i>x or i<x:
        List.append(i)
print(List)
        


[1, 2, 3, 4, 6, 7, 8, 9, 0]
